#!/bin/bash
num_of_fingers=$(ls /etc/fingers | wc -l)
random_finger=$(shuf -i 1-$num_of_fingers -n 1)
file="/etc/fingers/finger$random_finger"
delay=${1:-0.3}

while IFS= read -r var
do
    echo "$var"
    sleep $delay
done < "$file"
